services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  api:
    build: ./api
    container_name: api
    env_file:
      - ./api/.env
    ports:
      - "4000:4000"
    depends_on:
      - db

  front:
    build: ./frontend
    container_name: front
    env_file:
      - ./frontend/.env
    ports: 
      - "3000:80"
    depends_on:
      - api
    
volumes:
  db_data: